ZdruzenieSTROM/webstrom-frontend

package-lock.json
package.json

some packages (like TS types) belong to devDependencies, as they are needed only during development, they don't need to be installed on production.
I uninstalled those (`npm un xxx`) and installed them as such (`npm i -D xxx`).

reinstall @types packages as dev dependencies

---

.eslintrc
.prettierrc
.vscode/settings.json
README.md
package.json
src/Webstrom.tsx
src/components/Footer/Footer.tsx
src/components/Footer/index.tsx
src/components/MenuMain/MenuMain.tsx
src/components/MenuMain/index.tsx
src/components/MenuSeminars/MenuSeminars.tsx
src/components/MenuSeminars/index.tsx
src/index.tsx
src/pages/MainContentRouter/MainContentRouter.tsx
src/pages/MainContentRouter/index.tsx
src/pages/PagePlaceholder/PagePlaceholder.tsx
src/pages/PagePlaceholder/index.tsx
src/setupProxy.js
tsconfig.json
yarn.lock

ok, ja tu mam vlastne fungovat v slovencine, co... 😄 
- EDIT: luckily for us, create react app ma novu verziu `react-scripts`, kde updatlo eslint na v7 a spolu s nim ine configy. tak som updatol `react-scripts` na 4.0.0
- `eslint --init` inicializuje eslint - nainstalovalo to nejake package a urobilo robustnejsi config. upratal som ho a zbytocne package vyhodil (su pridane v ramci `react-scripts` packagu)
- ~create-react-app sa tvari, ze eslint, pluginy a configy maju fungovat defaultne, dokonca su aj v `yarn.lock`, no nesli mi, tak som ich rovno manualne nainstaloval vsetky (aspon mame nove verzie)~
- po kazdej zmene som pustil lint fix na vsetkych suboroch, aby bolo jasne, co ktory config spravil
- dali by sa prihadzat do `extends` este `jsx-a11y/recommended`, `import/recommended` a …

Setup ESLint with plugins

---

src/index.tsx

Pridal som do index.tsx nastavenia pre axios.
Teraz uz ma header prilozeny csrf token a teda post requesty funguju normalne. Malo by to aj vyriesit Matusov problem pri registracii.
Pri requestoch sa musi pouzivat relativna url /api/... a nie absolutna http://localhost:8000/...
Priklad:
```
axios.post('/api/user/login/', {
email: 'webmaster@strom.sk',
password: 'gumibanan',
})
.then(
(response) => {
console.log(response)
},
(error) => {
console.log(error)
},
)
```

fix axios post request

---

.eslintrc
src/components/Latex/Latex.tsx

for example it adds rules for changing `let` into `const` (if it is never redefined)

add @typescript-eslint with recommended config

---

src/pages/Router/Router.tsx
src/pages/VerifyEmail/VerifyEmail.tsx

Pridana cesta /verify-email/:verificationKey
verificationKey sa posle na /api/user/registration/verify-email. Mozne odpovede:
- 404: ak key nekoresponduje k ziadnemu emailu na overenie
- 200: ak sa email uspesne overil
Poznamka: zatial neexistuje v designe od Dorot miesto kde sa toto overovanie uskutocne alebo ako sa vyzerat odozva pre uzivatela, takze odpoved sa zatial len tak zobrazi ako string.

Add email verification page

---

package.json
src/admin/dataProvider.ts
src/admin/tokenAuthProvider.ts
src/pages/Admin/Admin.tsx
src/pages/Admin/Competition/CompetitionList.tsx
src/pages/Admin/Post/PostCreate.tsx
src/pages/Admin/Post/PostEdit.tsx
src/pages/Admin/Post/PostList.tsx
src/pages/Admin/Post/PostShow.tsx
src/pages/Router/Router.tsx
yarn.lock

Ako pisem v komentaroch, v podstate som vzal https://github.com/bmihelac/ra-data-django-rest-framework a prepisal pre nase ucely (napriklad v ich auth provideri sa pouziva local storage na ukladanie tokenu, a my uz vieme, ze to chceme mat v cookies -> hned prvy dovod napisat si providerov sami).
React Admin potrebuje dve zakladne veci - `dataProvider` a `authProvider`. Tak tieto mame uz napisane, aj ked mozno casom budeme robit nejake zmeny, ak budeme mat komplikovanejsie poziadavky.
Potom sa uz len definuje `Resource` a struktura rozhrania v Create/Edit/Show/List. Tieto vsetky som spravil pre Posty (`cms/post`) a len list pre `competition/series`.
PATCH a PUT requesty este nefunguju. Bud je chyba na strane BE, alebo nam musia dat lepsie info, ako tie requesty strukturovat. Rovnako bude …

Admin - cele manazovanie Postov, listovanie Serii

---

src/types/api/generated/base.ts
src/types/api/generated/cms.ts
src/types/api/generated/competition.ts
src/types/api/generated/personal.ts
src/types/api/generated/problem_database.ts
src/types/api/generated/user.ts

typy generovane z BE cez `django-typomatic` (BE PR: https://github.com/ZdruzenieSTROM/webstrom-backend/pull/101).
kazdy subor som preulozil, nech ho ESLint sformatuje.
kazdopadne... este som nemenil nas kod, aby tieto typy pouzival, nie su az take strong (je tam vela `any`, kde by som cakal `number`, atd.), a nechce sa mi tomu venovat, ked mam ine veci este na praci. Takze je tu novy task pre niekoho:
- zistit, preco tam django typomatic dava `any`, pozriet sa na BE alebo sa spytat chalanov, co je na tych fieldoch specialne, co realne mozeme pod tymi properties cakat, a potom to rucne prepisat.
- niektore fieldy su optional (otaznicek pri `id?` a `year?` atd.) - treba zistit preco a ci s nimi mozeme ratat, ze tam vzdy su, alebo nie.
ked budeme mat tie typy fajn, mozeme prepisovat kod aby …

Generovane API typy

---

package.json
pages/_app.tsx
src/components/FormItems/FormCheckbox/FormCheckbox.tsx
src/components/FormItems/FormInput/FormInput.tsx
src/components/FormItems/FormSelect/FormSelect.tsx
src/components/Latex/Latex.tsx
src/components/Latex/LatexExample.tsx
src/components/Marquee/Marquee.tsx
src/components/Overlay/Overlay.tsx
src/components/PageLayout/PageLayout.tsx
src/components/PageLayout/components/Authentication.tsx
src/components/PageLayout/components/Footer.tsx
src/components/PageLayout/components/LoginForm.tsx
src/components/PageLayout/components/MenuMain.tsx
src/components/PageLayout/components/MenuSeminars.tsx
src/components/ScrollingText/ScrollingText.tsx
src/pages/Admin/Admin.tsx
src/pages/Admin/Competition/CompetitionList.tsx
src/pages/Admin/Post/PostCreate.tsx
src/pages/Admin/Post/PostEdit.tsx
src/pages/Admin/Post/PostList.tsx
src/pages/Admin/Post/PostShow.tsx
src/pages/PagePlaceholder/PagePlaceholder.tsx
src/pages/Post/Post.tsx
src/pages/RegisterForm/RegisterForm.tsx
src/pages/VerifyEmail/VerifyEmail.tsx
yarn.lock

based on #27, potom rebasnem
React 17 podporuje novy JSX transform, co znamena, ze pre pouzitie JSX v komponentoch netreba mat `React` import. tu je nieco viac o tom: https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html#removing-unused-react-imports
spustil som spominany codemod, eslint --fix a doupravil vsetky zvysne importy, nech uz destructurujeme vsetko.

Upgrade reactu na v17

---

src/components/Admin/custom/MyArrayField.tsx

robilo to ESLint error, aj ked funkcne to asi slo, kedze je `@material-ui/core` subdependencia react admina

Fix Material UI import in react admin

---

src/pages/strom/index.tsx

remove `contentWidth` on `/strom` for consistency

---

src/components/Archive/Archive.tsx
src/components/PageLayout/MenuMain/MenuMain.tsx
src/components/Post/Post.tsx
src/components/Problems/Problems.tsx
src/components/Problems/SemesterPicker.tsx
src/components/RegisterForm/RegisterForm.tsx
src/components/Results/Results.tsx
src/components/VerifyEmail/VerifyEmail.tsx
src/pages/strom/[page].tsx
src/pages/strom/akcie/[[...params]].tsx
src/utils/AuthContainer.tsx
src/utils/ProfileContainer.tsx

https://github.com/ZdruzenieSTROM/webstrom-frontend/blob/master/docs/trailing-slash.md vysvetluje, ako vlastne requesty chceme definovat bez koncoveho lomitka, lebo tam inak next.js dava zbytocny 308 redirect, aj ked to potom rewrite v `next.config.js` prepise do formatu s lomitkom 😄 trochu zmatok, ale co uz

Remove trailing slash from requests to avoid the unnecessary 308 redirect from next.js side

---

.eslintrc.js
package.json
src/pages/_app.tsx
yarn.lock

there are some good quality-of-life changes in 5.0.0, e.g. they changed the focus handling, so the queries are now not refetched when clicking into Chrome DevTools and back

Upgrade `react-query` to 5.0.0 alpha

---

.gitignore
tsconfig.json

next.js automatically changes `tsconfig.json` to allow incremental build. why not

Typescript incremental build

---

src/components/Archive/Archive.tsx
src/components/Clickable/Clickable.tsx
src/components/Problems/Problems.tsx

Otvaranie PDF nahrateho/opraveneho riesenia v novom tabe

---

src/components/PageLayout/Authentication/Authentication.tsx
src/components/Profile/ProfileDetail.module.scss
src/components/Profile/ProfileDetail.module.scss.d.ts
src/components/Profile/ProfileDetail.tsx
src/pages/malynar/profil/index.tsx
src/pages/matik/profil/index.tsx
src/pages/strom/profil/index.tsx
src/types/api/personal.ts

first part of https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/56

Profil page

---

package.json
src/components/PageLayout/LoginForm/LoginForm.tsx
src/components/Profile/ProfileDetail.tsx
src/components/Profile/ProfileForm.tsx
src/components/RegisterForm/RegisterForm.tsx
src/components/SchoolSubForm/SchoolSubForm.tsx
src/pages/strom/profil/uprava.tsx
yarn.lock

2. cast https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/56
formular na upravu udajov uzivatela
P.S.: prve dva commity su z ineho PR

Profil - Uprava udajov

---

src/components/SemesterAdministration/SemesterAdministration.tsx

Add: Add competitors export

---

src/components/Problems/Problem.module.scss
src/components/Problems/Problem.module.scss.d.ts
src/components/Problems/Problem.tsx
src/components/Problems/Problems.module.scss
src/components/Problems/Problems.tsx
src/components/SemesterAdministration/SemesterAdministration.module.scss
src/components/SemesterAdministration/SemesterAdministration.module.scss.d.ts
src/components/SemesterAdministration/SemesterAdministration.tsx

Remove i want to participate

---

src/components/Dialog/Dialog.tsx
src/components/Profile/PasswordChangeForm.tsx
src/components/Profile/ProfileDetail.tsx
src/theme.ts

final part of https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/56

Zmena hesla

---

src/components/Profile/ProfileDetail.module.scss
src/components/Profile/ProfileDetail.module.scss.d.ts
src/components/Profile/ProfileDetail.tsx

Solve https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/204

Change Profil detail according to design

---

src/components/Admin/Competition/CompetitionList.tsx
src/components/Admin/custom/MyArrayField.tsx
src/components/Admin/custom/MyDateInput.tsx
src/components/Admin/custom/MyEditActions.tsx
src/components/Admin/custom/MyShowActions.tsx
src/components/Admin/dataProvider.ts
src/components/Admin/resources/cms/post/PostCreate.tsx
src/components/Admin/resources/cms/post/PostEdit.tsx
src/components/Admin/resources/cms/post/PostList.tsx
src/components/Admin/resources/cms/post/PostShow.tsx
src/components/PageLayout/MenuMain/MenuMain.module.scss
src/components/PageLayout/MenuMain/MenuMain.module.scss.d.ts
src/components/PageLayout/MenuMain/MenuMain.tsx

niektore veci som actually vytiahol z mojho uz pol roka otvoreneho tabu 😄 https://marmelab.com/react-admin/Upgrade.html
prerobeny React Admin data provider na to, aby pouzival axios, takze vyuziva uz definovany axios interceptor v AuthContaineri, ktory pridava `X-CSRFToken` hlavicku do requestov... a tak, no 😄

React admin csrf and other fixes

---

src/pages/strom/akcie/[[...params]].tsx
src/utils/formatDate.ts

jediny use datumov na stranke bol zatial na stranke akcii. po https://github.com/ZdruzenieSTROM/webstrom-backend/pull/258 ho treba zmenit.
zatial neoveritelne, kym nefunguje administracia eventov

Update event dates to new BE format

---

src/components/Problems/Problem.tsx
src/components/Problems/Problems.tsx
src/components/Problems/UploadProblemForm.module.scss
src/components/Problems/UploadProblemForm.module.scss.d.ts
src/components/Problems/UploadProblemForm.tsx
src/types/api/competition.ts

solve https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/130

File uploader  - uprava upozorneni

---

src/components/Profile/PasswordChangeForm.tsx
src/components/Profile/ProfileForm.tsx

Close and back button in profile changes

---

src/components/VerifyEmail/VerifyEmail.tsx

176 email verification landing page

---

src/components/PageLayout/Authentication/Authentication.tsx
src/components/PageLayout/LoginForm/LoginForm.tsx

added redirections after logging in or out

---

src/components/PageLayout/PageLayout.tsx
src/pages/malynar/index.tsx
src/pages/matik/index.tsx
src/pages/strom/index.tsx
src/pages/strom/vysledky/[[...params]].tsx
src/pages/strom/zadania/[[...params]].tsx

Close #229 
Dáva to názov vo formáte "page_title | seminar_name"

Add head-title to pages

---

src/components/Admin/custom/MyCreate.tsx
src/components/Admin/custom/MyEdit.tsx
src/components/Admin/resources/competition/event/EventCreate.tsx
src/components/Admin/resources/competition/event/EventEdit.tsx
src/components/Admin/resources/competition/event/EventList.tsx
src/components/Admin/resources/competition/event/EventShow.tsx

eventy v react adminovi sa uz daju vytvarat a editovat, s alebo bez registracneho linku, a teda bez publications.
publications handling treba osobitne nakodit. mozeme nechat otvoreny #141 a prepisat ho na handling publications k eventom.

React Admin - Functional events create/edit

---

src/components/SemesterAdministration/SemesterAdministration.module.scss
src/components/SemesterAdministration/SemesterAdministration.tsx
src/types/api/generated/competition.ts

Pribudlo osobitne generovanie jednotlivych serii v semestri.
Closes #169

Generate results for series in administration

---

src/components/Results/ResultsRow.module.scss
src/components/Results/ResultsRow.tsx

Close #219 
Neviem ci takto to je dobre, ale vyzera to teraz uplne rovnako ako predtym, akurat pri hoveri podfarbi cely riadok

Podfarbenie celeho riadka vo vysledkovke

---

src/components/PageLayout/Authentication/Authentication.module.scss
src/components/PageLayout/MenuMain/MenuMain.module.scss
src/components/PageLayout/MenuMain/MenuMain.module.scss.d.ts
src/components/PageLayout/MenuMain/MenuMain.tsx

Close #274 
Pridané skrolovanie, ak je viac položiek (aktuálne sa to deje len vedúcim).

Add scrollbar to menu

---

src/theme.ts

netestoval som ziadny inu stranku, ktoru by toto mohlo rozbit.
EDIT: ok, par som ich preklikal, vyzera to ok.
before:
now:

Map Typography variants to span element

---

src/components/PageLayout/LoginFormWrapper/LoginFormWrapper.tsx
src/components/Problems/Problem.tsx
src/components/Problems/Problems.tsx

Login popup when submitting done properly

---

src/components/Admin/Admin.tsx
src/components/Admin/dataProvider.ts
src/components/Admin/resources/competition/competition/CompetitionEdit.tsx
src/components/Admin/resources/competition/competition/UpcomingOrCurrentEvent.tsx
src/components/Admin/resources/competition/semester/SemesterCreate.tsx
src/components/Admin/resources/competition/semester/SemesterEdit.tsx
src/components/Admin/resources/competition/semester/SemesterList.tsx
src/components/Admin/resources/competition/semester/SemesterShow.tsx
src/components/Admin/resources/competition/series/SeriesCreate.tsx
src/components/Admin/resources/competition/series/SeriesList.tsx
src/components/Admin/resources/competition/series/SeriesShow.tsx

mal by teraz fungovat reasonable Create/Edit na Semestroch aj na Seriach.
related sety sa excluduju z edit requestov (aj ked ich uz BE nechrume, ignoruje ich) a treba ich vsetky handlovat a nalinkovat osobitne.
len maly prehlad:
- Competition ma Eventy -> pri edite Eventu sa voli Competion, ku ktorej patri ✅ 
- Event maju Publikacie -> treba zrobic edit Publikacii ❌ 
- pri edite Semestru sa voli Competion, ku ktorej patri ✅ 
- Semester ma Serie -> pri edite Serie sa voli semester, ku ktoremu patri ✅ 
- Semester ma Publikacie -> treba zrobic edit Publikacii ❌ 
- Semester ma Late tagy -> actually tieto sa vyberaju priamo pri edite Semestra a budu vzdy prepisovat aktualny array ✅ 
- Seria ma Problemy -> treba zrobic edit Problemov ❌ 
zatvorime tieto (closes #290 #188) a pre #188 spravime …

React Admin - Semester, Serie

---

src/components/Admin/resources/cms/post/PostList.tsx
src/components/PageLayout/LoginFormWrapper/LoginFormWrapper.tsx
src/components/PageLayout/PasswordResetRequest/PasswordResetRequest.tsx
src/components/PasswordReset/PasswordReset.tsx
src/components/PasswordResetSent/PasswordResetSent.tsx
src/components/Posts/Post.tsx
src/components/Verification/Verification.tsx
src/pages/malynar/reset-sent/index.tsx
src/pages/malynar/verifikacia/[[...params]].tsx
src/pages/matik/reset-sent/index.tsx
src/pages/matik/verifikacia/[[...params]].tsx
src/pages/strom/archiv/[[...params]].tsx
src/pages/strom/reset-password/[...resetToken].tsx
src/pages/strom/reset-sent/index.tsx
src/pages/strom/verifikacia/[[...params]].tsx

(2/2)
* Added reset form
* Adjusted visuals
* Adjusted landing page messages
* Adjusted redirects
closes #192

Password reset - reset form

---

src/components/Admin/dataProvider.ts

fixuje spravanie napr. pri edite Post linkov - posielame tam cely array (viac info tu: https://github.com/ZdruzenieSTROM/webstrom-backend/issues/327), presnejsie uplne cely Post objekt. BE nested serializer sa z nejakeho dovodu sprava inak, ak je `id` v body toho requestu, a byt tam nemusi (nema), kedze je sucastou URL

React Admin: remove `id` from PATCH (edit) body

---

src/components/Clickable/Clickable.module.scss
src/components/Posts/Post.tsx
src/components/Posts/PostDetail.tsx
src/components/Posts/PostMarkdown.tsx
src/components/Posts/PostMarkdownTexts.tsx
src/components/Posts/Posts.tsx
src/components/Problems/Problems.module.scss
src/components/StaticSites/Markdown.tsx
src/components/StaticSites/Texts.tsx
src/pages/malynar/index.tsx
src/pages/matik/index.tsx
src/pages/strom/index.tsx
src/theme.ts

close #261 
nastyloval som novy markdown a zakazal som v nom tabulky, mozno som ich tam mohol nechat, ale osobne si myslim ze to tam nepatri

Posts Detail

---

src/components/PageLayout/PageLayout.tsx

Single text node as browser title to fix warning

---

src/components/Problems/Problem.tsx

Closes #330 
Mozno by tam mohlo pisat nejaku hlasku, ked nemozes odovzdat kvoli zlemu rocniku, zatial to je len disabled button, ako ked je to po termine.

Fix problem submition

---

src/components/Posts/Post.tsx
src/index.scss
src/pages/_app.tsx
src/pages/_document.tsx
src/theme.ts

1. fixes #328 - neviem ako s nacitavanim stranky, ale toto je novy system, ktorym sa maju servovat fonty priamo od nas, ziadny osobitny request na google z browseru
2. ta som zas prerobil definicie fontov, lebo nieco malo defaultne styly a bralo to napr. fontFamily z temy, niektore nie...
3. vlastna postDate varianta s fontWeight 300, ktory narozdiel of 275 aj existuje

New font loading using next/font package

---

src/components/Dialog/Dialog.tsx
src/components/PageLayout/Authentication/Authentication.tsx
src/components/PageLayout/LoginForm/LoginForm.tsx
src/components/PageLayout/LoginFormWrapper/LoginFormWrapper.tsx
src/components/PageLayout/PasswordResetRequest/PasswordResetRequest.tsx
src/components/Problems/Problems.tsx
src/components/Profile/PasswordChangeForm.tsx
src/theme.ts

solve https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/213

Fixed behavior of size of dialogs

---

package.json
src/components/Admin/Admin.tsx
src/components/Admin/custom/LatexPreview.tsx
src/components/Admin/custom/MyEditActions.tsx
src/components/Admin/custom/MyFileField.tsx
src/components/Admin/custom/MyImageField.tsx
src/components/Admin/dataProvider.ts
src/components/Admin/resources/competition/problems/ProblemCreate.tsx
src/components/Admin/resources/competition/problems/ProblemEdit.tsx
src/components/Admin/resources/competition/problems/ProblemList.tsx
src/components/Admin/resources/competition/problems/ProblemShow.tsx
src/components/Admin/resources/competition/problems/createProblemFormData.ts
yarn.lock

fixes #311 
po tomto by malo ist vytvorit:
- novy semester pod competition
- novu seriu pod semestrom
- nove ulohy pod seriou
ulohy este nemaju:
- ~obrazok - uploadovanie obrazku bude trochu problem - treba pripravit react admina (dataProvider, alebo manualne v tomto pripade), aby vedel poslat bud klasicky JSON data, alebo multipart/form-data, kde je aj obrazok~
- komentare - zobrazit vsetky niekde na detaili ulohy?
- ~latex preview~
create problem pada s 500, BE issue tu: https://github.com/ZdruzenieSTROM/webstrom-backend/issues/368

React Admin: Problems administration

---

src/components/Admin/custom/FlatpagePreview.tsx
src/components/Admin/custom/PostPreview.tsx
src/components/Admin/resources/base/flat-page/FlatpageCreate.tsx
src/components/Admin/resources/base/flat-page/FlatpageEdit.tsx
src/theme.ts

fixes #259 
collapsed:
expanded:

259:  Flatpage create/edit preview

---

src/components/Clickable/Link.tsx
src/components/Problems/UploadProblemForm.tsx

Closes #345 Treba to nejako vizualne vyriesit.

Text for tips how to upload solution

---

src/components/PageLayout/LoginForm/LoginForm.tsx

Without / at the start, it redirects relatively e. g. from /matik/akcie/lomihlav to /matik/akcie/lomihlav/matik/registracia
Fixes #399

Fix: LoginForm.tsx incorrect registration link in login dialog.

---

src/components/PageLayout/MenuMain/MenuMain.tsx

Allowed links to external websites in menu items

---

src/components/CompetitionPage/CompetitionPage.tsx
src/components/CompetitionPage/UpcomingOrCurrentEventInfo.tsx
src/components/Problems/Problem.tsx
src/types/api/competition.ts
src/utils/formatDate.ts

Spolieha na branch `registration_link_str` ... kym sa nemergne do mastra

Competition page content

---

src/components/Dialog/Dialog.tsx
src/components/RegisterForm/RegisterForm.tsx
src/theme.ts
src/utils/useNavigationTrap.ts

413 tlačidlo gpdr pri registrácií opraviť

---

src/components/Results/Results.tsx
src/components/Results/ResultsRow.tsx
src/theme.ts

fixes #386 
daco som prestyloval, ale ja nevjem us... treba mozno spolu doladit zas nejake hodnoty.

fix #386 - restyle Results

---

src/components/RegisterForm/RegisterForm.tsx

Not really error, tel. číslo je nepovinný údaj. Ak je zlé, je to chyba používateľa, keďže kratšie čísla musia byť akceptované, najmä kvôli kratším predvoľbám.
closes #436

Changed error message

---

src/components/Admin/resources/cms/post/PostCreate.tsx
src/components/Admin/resources/cms/post/PostEdit.tsx

RA now validates mas length of 200 characters on Post text

---

src/components/Admin/custom/PostPreview.tsx
src/components/Posts/PostDetail.tsx
src/components/Posts/Posts.tsx

Added close button to PostDetail

---

src/components/Problems/UploadProblemForm.tsx

Displaying error message whne uploading a solution in format other than pdf

---

next.config.ts
src/components/Crossroad/Crossroad.tsx
src/pages/index.tsx
src/svg/strom.svg
src/theme.ts

Add Crossroad for root page

---

src/components/Admin/AdminLayout.tsx
src/components/Admin/useAuthProvider.ts
src/components/PageLayout/LoginForm/LoginForm.tsx
src/components/PageLayout/MenuMain/BottomButtons.tsx
src/components/PasswordReset/PasswordReset.tsx

Redirect to seminar instead of '/' if possible

---

src/theme.ts

fix #490
snad mame vsetky texty obalene v Typography, nic som nenasiel co by nebolo a bilo by do oci

Add justify to body typographies

---

src/components/Crossroad/Crossroad.tsx
src/components/PageLayout/MenuMain/MenuMain.tsx
src/components/PageLayout/PageLayout.tsx
src/components/PageLayout/StromLogo/StromLogo.tsx
src/svg/strom.svg

resolve #383 . Je este potrebne vytvorit asi nejaky hook co bude pocitat kde sa to ma zobrazit, lebo bez banneru to nebude sediet a to iste pre niektore konkretne sirky obrazovky

Enable main menu and fix tree

---

src/pages/_app.tsx

Change default title

---

src/components/Admin/custom/list-filtering/CompetitionSeminarFilterSection.tsx
src/components/Admin/custom/list-filtering/EventFilterSection.tsx
src/components/Admin/custom/list-filtering/GradeFilterSection.tsx
src/components/Admin/custom/list-filtering/SeasonCodeFilterList.tsx
src/components/Admin/resources/competition/event-registration/EventRegistrationList.tsx
src/components/Admin/resources/competition/event/EventList.tsx
src/components/Admin/resources/competition/problems/ProblemList.tsx
src/components/Admin/resources/competition/semester/SemesterList.tsx
src/components/Admin/resources/competition/series/SeriesList.tsx

ciastocne resolve #527 (mozno aj uplne, a zvysne TODO posuvam do noveho issue do dalsieho milestone, idealne to riesit az podla potreby uzivatelov)

Add more filters to React Admin

---

src/components/Marquee/Marquee.tsx
src/components/PageLayout/Banner/Banner.tsx
src/pages/_app.tsx
src/utils/BannerAnimationProvider.tsx

Banner - pause/play

---

src/components/SemesterAdministration/SemesterAdministration.tsx
src/types/api/generated/competition.ts

nasiel som @kovacspe branch spred 11 hodin, mozno chce(l) spravit PR 😄

Transformovaný zoznam úloh na tabulku

---

src/components/Problems/Discussion.tsx
src/components/Problems/Problems.tsx
src/components/Profile/ProfileDetail.tsx
src/components/Profile/ProfileForm.tsx
src/utils/useProfile.ts

Create `useProfile` hook

---

src/components/PageLayout/Header/HeaderHeightContainer.tsx
src/components/PageLayout/PageLayout.tsx
src/components/PageLayout/StromLogo/StromLogo.tsx
src/components/PageLayout/TopGrid/TopGrid.tsx
src/components/Posts/Posts.tsx
src/svg/strom.svg

Solve positioning of Tree on left
