ZdruzenieSTROM/webstrom-frontend

- README.md
- package.json
- yarn.lock
Odstranil som warningy pocas spustenie `yarn` a jemne aktualizovat `README.md`.
> Follow up eslint changes

- src/Webstrom.tsx
- src/components/MenuMain/MenuMain.tsx
- src/components/MenuSeminars/MenuSeminars.tsx
- src/index.tsx
- src/pages/MainContentRouter/MainContentRouter.tsx
Prerobil som kusok router.
- Nepouzivame viac subdomeny ale cestu za domenou, napriklad "malynar.strom.sk/" sa zmeni na "strom.sk/malynar/"
- Trochu som sprehladnil kod na zobrazovanie horneho a bocneho menu
> Router update

- package.json
- src/components/Latex/Latex.tsx
- src/components/Latex/LatexExample.css
- src/components/Latex/LatexExample.tsx
- src/pages/Router/Router.tsx
- yarn.lock
Co som pridal:
- mathjax-full package - core funkcionalita mathjaxu
- mathjax-react package - maly wrapper nad mathjaxom na jednoduche renderovanie
- Latex component - component ktory text v <Latex>text</Latex> rozdeli na casti ktore su medzi $.$ \(.\) $$.$$ \[.\], tie natechuje a zobrazi ako inline alebo diplay mathjax a potom na casti ktore su mimo a tie necha ako obycajny text.
- LatexExample component - jednoducha textarea na input a pod nou sa zobrazuje vyrenderovany matematicky text
- router cesta example/latex - nech si mozeme testovat lahko komponenty ktore vytvarame a davat ich do /example/ cesty a neskor ich naraz poodstranujeme ked ich nebude treba. Pripadne ich mozeme pouzit ako priklad toho ako sa niektore komponenty daju na stranke pouzivat.
> Latex component

- package.json
- src/components/Marquee/Marquee.scss
- src/components/Marquee/Marquee.tsx
- src/components/PageLayout/PageLayout.tsx
- src/components/ScrollingText/ScrollingText.scss
- src/components/ScrollingText/ScrollingText.tsx
- yarn.lock
Pridane:
- node-sass package - umoznuje pouzivat scss sass subory miesto css bez potreby prekompilacie
- Marquee komponent - komponent ktory scrolluje akykolvek ReactNode zo strany na stranu. Momentalne sa pouziva len ako pomocny komponent ale je moznost ho pouzit aj nezavysle preto som ho nechal top level components priecinku
- ScrollingText komponent - zobrazuje text na stranku pomocou Marquee komponentu. Zatial ale este neexistuje api point na tento text takze tento request na api point pridam az neskor. Zatial ma len fixny text na ukazku.
> add ScrollingText component

- src/pages/Router/Router.tsx
Pri mergeovani PR od Mata som zle vyriesil jeden konflikt
> resolving wrong conflict change

- package.json
- src/Webstrom.tsx
- src/components/Marquee/Marquee.tsx
- src/components/Overlay/Overlay.scss
- src/components/Overlay/Overlay.tsx
- src/components/PageLayout/components/Authentication.scss
- src/components/PageLayout/components/Authentication.tsx
- src/components/PageLayout/components/Footer.css
- src/components/PageLayout/components/Footer.tsx
- src/components/PageLayout/components/LoginForm.scss
- src/components/PageLayout/components/LoginForm.tsx
- src/components/PageLayout/components/MenuMain.tsx
- src/index.tsx
- yarn.lock
Pridane/zmenene veci:
**Overlay komponent:**  vytvori overlay v ktorom sa daju zobrazovat komponenty mimo obsahu stranky. Zatial sa tento overlay zobrazuje staticky nad celou strankou, neskor pridam moznost zobrazivat ho nad aktualnym html elementom v ktorom sa nachadza, bude to potrebne neskor na zobrazovanie detailov postov alebo zobrazovanie diskusii.
**Authentication komponent:** je to komponent v MenuMain ktory zobrazuje "odhlasit" button v pripade ze je uzivatel prihlaseny alebo "registrovat" a "prihlasit" buttony ktore zobrazia overlay ktory ma v strede registracny/prihlasovaci form.
**LoginForm komponent:** je to komponent ktory zabezpecuje renderovanie formu na prihlasovanie a zastresuje prihlasovanie na submit event.
**Nacitanie menu itemov:** useEffect v MenuMain, ktory …
> Login form

- next.config.js
~based on #27, potom rebasnem~
je to sice riadok kodu, ale tak nechcel som vsetko rvat do jedneho PR 😄
> Znovupovolenie react strict modu v nexte

- yarn.lock
~based on #27, potom rebasnem.~
pustenie eslintu hadzalo warning ohladom outdated browserslistu, a ze mame pustit `npx browserslist@latest --update-db`, tak som pustil.
> Update browserslist db

- src/components/Problems/Discussion.tsx
odkomentoval som delete comment lebo uz to ide aj na BE
> Samo: uncomment delete comment

- src/components/Problems/Problems.tsx
velmi docasne tlacitka na demonstraciu funkcnosti pozerania rieseni
> Samo: solution buttons

- src/components/PageLayout/Authentication/Authentication.tsx
- src/components/PageLayout/Footer/Footer.tsx
- src/components/PageLayout/LoginForm/LoginForm.tsx
- src/pages/_app.tsx
- src/utils/AuthContainer.tsx
treba mergnut/nasadit naraz s https://github.com/ZdruzenieSTROM/webstrom-backend/pull/139
> Auth rework - use only session auth, remove cookie handling

- docs/trailing-slash.md
len ze ako funguje koncove lomitko, lebo je to kus crazy...
> document current trailing slash handling mechanisms

- src/components/Problems/Problems.module.scss
- src/components/Problems/Problems.tsx
related to #60 
tak nejak to vyzera:
> Pridane styly do buttonov

- src/types/api/base.ts
- src/types/api/cms.ts
- src/types/api/competition.ts
- src/types/api/generated/competition.ts
- src/types/api/generated/personal.ts
- src/types/api/personal.ts
- src/types/api/problem_database.ts
- src/types/api/user.ts
Boli pridane interfaci upravene z generovanych, ktore obsahuju hadam spravne typy, aby sme si ich uz nemuseli predefinovavat v komponentoch.
> Upravene generovane typy

- .eslintrc.js
- src/components/Archive/Archive.module.scss
- src/components/Archive/Archive.module.scss.d.ts
- src/components/Archive/Archive.tsx
- src/components/Problems/Problems.tsx
- src/pages/malynar/archiv/[[...params]].tsx
- src/pages/matik/archiv/[[...params]].tsx
- src/pages/strom/akcie/[[...params]].tsx
- src/pages/strom/archiv/[[...params]].tsx
Treba to ešte nejako naformátovať.
> Archív seminárov

- src/components/Problems/Discussion.module.scss
- src/components/Problems/Problems.module.scss
- src/components/Problems/Problems.tsx
- src/components/Problems/SideContainer.module.scss
- src/utils/AuthContainer.tsx
- src/utils/NiceBytes.tsx
- src/utils/niceBytes.ts
dajake zmeny, upravy a vylepsenia
> sidebar zmeny

- src/components/Latex/Latex.module.scss
- src/components/Latex/Latex.module.scss.d.ts
- src/components/Latex/Latex.tsx
- src/components/Problems/Discussion.module.scss
- src/components/Problems/Problems.module.scss
- src/components/Problems/SideContainer.tsx
- src/index.scss
- src/index.scss.d.ts
- src/pages/_app.tsx
in web development, there's a good practice to "reset" some default browser CSS styles so it's easier and more predictable to style stuff. I used this guy's reset rules while keeping most of our global styles defined, too: https://www.joshwcomeau.com/css/custom-css-reset/
This guy (Josh Comeau) has really nice React and CSS blogs, has a whole CSS course, also prepares a React one, and teaches this stuff at university, so I guess he knows what he's talking about 😄
> Global CSS reset

- package.json
- src/components/Problems/Problems.module.scss
- src/components/Problems/Problems.module.scss.d.ts
- src/components/Problems/Problems.tsx
- src/pages/_app.tsx
- yarn.lock
React Query je go-to libka na riesenie queries (GET requesty) a mutations (POST requesty) s loading a error stavmi, refetchov, cache, atd. Zjednodusuje to ten nas opakovany kod s axiosom v try-catch bloku.
Pustil som sa tu aj do vacsej prerabky `Problems.tsx`, tak mame riadny example, ako to moze vyzerat.
~TODO:~
- ~prerobit este submit registracie do serie na mutation~
- ~refetch pri prihlaseni do stranky~
- ~refetch pri prihlaseni do serie~
- ~upgrade na `@tanstack/react-query` (nevsimol som si, ze to premenovali a nove verzie vydavaju pod inym menom)~
> Setup React Query and rework Problems using it

- package.json
- src/components/Problems/Discussion.module.scss
- src/components/Problems/Discussion.module.scss.d.ts
- src/components/Problems/Discussion.tsx
- src/components/Problems/Problems.module.scss
- src/components/Problems/Problems.module.scss.d.ts
- src/components/Problems/Problems.tsx
- src/components/Problems/SemesterPicker.module.scss
- src/components/Problems/SemesterPicker.module.scss.d.ts
- src/components/Problems/SemesterPicker.tsx
- src/components/Problems/SideContainer.module.scss
- src/components/Problems/SideContainer.module.scss.d.ts
- src/components/Problems/SideContainer.tsx
- src/components/Problems/UploadProblemForm.module.scss
- src/components/Problems/UploadProblemForm.module.scss.d.ts
- src/components/Problems/UploadProblemForm.tsx
- src/pages/_app.tsx
- src/utils/AuthContainer.tsx
- yarn.lock
zaujimavosti:
- pridany globalny error handler - pri mutaciach sa teraz vzdy skusi pozriet `response.data.detail` a vyhodit browser alert s nasou slovenskou spravou. nemusime tym padom riesit iny error handling lokalne
- oddelene nejake komponenty do vlastnych suborov
- zmazane niektore zbytocne API typy
- prepisany Discussion komponent pomocou React Query
- prestylovany side container a jeho pouzitia, fixnute nejake problemy s tym
> Refactor UploadProblemForm and Discussion

- src/utils/AuthContainer.tsx
toto je kus tricky vec, tak som to lepsie popisal
> Better document 403 interceptor

- .eslintrc.js
- package.json
- src/components/Archive/Archive.tsx
- src/components/Latex/Latex.tsx
- src/pages/_app.tsx
- yarn.lock
I consider all the 15 warnings left now useful and eventually removed by features
> ESLint adjustments to remove most warnings

- src/components/Problems/Discussion.tsx
- src/components/Problems/Problems.tsx
- src/utils/AuthContainer.tsx
jednotne miesto pre pustenie refetchu dat pri prihlaseni/odhlaseni
> Global place to invalidate (refetch) queries on login/logout

- src/components/Problems/Problems.module.scss
- src/components/Problems/Problems.module.scss.d.ts
- src/components/Problems/Problems.tsx
> Admin link na opravovanie

- src/components/Problems/Discussion.tsx
- src/utils/AuthContainer.tsx
current state:
https://user-images.githubusercontent.com/6044119/233430503-a7a7264a-0d63-4a2f-b99d-87e6709992e9.mp4
> Better comments buttons

- src/components/RegisterForm/RegisterForm.tsx
> Add seminar to registration request

- src/components/FileDropZone/FileDropZone.module.scss
- src/components/FileDropZone/FileDropZone.module.scss.d.ts
- src/components/FileDropZone/FileDropZone.tsx
- src/components/ProblemAdministration/ProblemAdministration.module.scss
- src/components/ProblemAdministration/ProblemAdministration.module.scss.d.ts
- src/components/ProblemAdministration/ProblemAdministration.tsx
- src/components/Problems/UploadProblemForm.module.scss
- src/components/Problems/UploadProblemForm.module.scss.d.ts
- src/components/Problems/UploadProblemForm.tsx
and make FileDropZone separate component
> Rework table for setting score to grid

- src/components/PageLayout/Footer/Footer.module.scss
- src/components/PageLayout/MenuMain/MenuMain.module.scss
- src/components/PageLayout/MenuMain/MenuMain.tsx
- src/components/PageLayout/MenuSeminars/MenuSeminars.module.scss
- src/components/PageLayout/PageLayout.module.scss
- src/components/PageLayout/PageLayout.module.scss.d.ts
- src/components/PageLayout/PageLayout.tsx
zacal som sa hrat s prilis vela vecami naraz, tak aspon pokus nieco male oddelit.
text menu vyzera mozno obrovsky, ale realne v celom dizajne mame vacsie fonty a vsetko, tak skusim pozvacsovat aj zvysok a uvidime, ako sme s tym spokojni
> Menu from top, bigger and uppercase menu items, and small refactors

- src/components/Archive/Archive.tsx
- src/components/PageLayout/MenuMain/MenuMain.module.scss
- src/components/PageLayout/MenuMain/MenuMain.module.scss.d.ts
- src/components/PageLayout/MenuMain/MenuMain.tsx
- src/components/Posts/Posts.tsx
- src/components/RegisterForm/RegisterForm.tsx
after #145 and this PR, we have all previous manual `useEffect` fetching replaced by `useQuery`.
> Rest of `useQuery` usages

- .eslintrc.js
- next.config.js
- package.json
- src/components/CloseButton/CloseButton.module.scss
- src/components/CloseButton/CloseButton.module.scss.d.ts
- src/components/CloseButton/CloseButton.tsx
- src/components/PageLayout/MenuMain/MenuMain.module.scss
- src/components/PageLayout/MenuMain/MenuMain.module.scss.d.ts
- src/components/PageLayout/MenuMain/MenuMain.tsx
- src/components/Problems/SideContainer.module.scss
- src/components/Problems/SideContainer.module.scss.d.ts
- src/components/Problems/SideContainer.tsx
- src/components/Problems/UploadProblemForm.module.scss
- src/components/Problems/UploadProblemForm.tsx
- src/svg/close.svg
- src/svg/menu.svg
- svgo.config.js
- tsconfig.json
- yarn.lock
use icons from the design - though I had to play with the hover effect so it looks at least a bit reasonable
https://github.com/ZdruzenieSTROM/webstrom-frontend/assets/6044119/d55b9f28-bc94-4333-a73b-3f437aa9e4a4
https://github.com/ZdruzenieSTROM/webstrom-frontend/assets/6044119/ae7ca07f-8660-40ab-b772-1fccd54acb59
> Revisit menu and close icons

- src/components/Problems/Discussion.tsx
- src/components/Problems/Problems.tsx
publish comment a hide comment to sice actually nepotrebuju, lebo comment count obsahuje aj schovane komentare... ale v ramci konzistencie je to asi lepsie takto
fixes #122
> Update comment count after manipulating comments

- src/components/FileUploader/FileUploader.tsx
- src/components/PublicationUploader/PublicationUploader.tsx
- src/components/SemesterAdministration/SemesterAdministration.tsx
- src/types/api/competition.ts
- src/types/api/generated/competition.ts
> Upload of publications in administration

- src/pages/strom/akcie/[[...params]].tsx
- src/pages/strom/akcie/competition.module.scss
- src/pages/strom/akcie/competition.module.scss.d.ts
Na stranku sutaze je pridany popis aktualneho rocnika - odkedy, dokedy, registracia,... Treba tam este mozno lepsie vyriesit odkaz na pozvanku. Zmenila som este v archive, nech su publikacie Link a daju sa stiahnut.
> Events page - info about current semester

- src/components/ProblemAdministration/ProblemAdministration.tsx
Aktualne to stahuje, ale na backende sa vyriesi aby to zobrazovalo v prehliadaci. Closes #184
> Zmena linku na zobrazenie rieseni v administracii

- src/components/Profile/ProfileForm.tsx
- src/components/RegisterForm/RegisterForm.tsx
> feat(reg, user): changed phone number format submitted to server

- src/components/Latex/Latex.tsx
solve https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/198
> Render HTML in Problem

- src/components/Problems/Discussion.module.scss
- src/components/Problems/Discussion.module.scss.d.ts
- src/components/Problems/Discussion.tsx
Keď uživateľ nie je prihlásený, tak mu v diskusii namiesto miesta na písanie komentára a a tlačítka odoslať je hláška o tom, že sa musia prihlásiť. Možno to treba nejak krajšie nastylovať. Closes #189
> Pridanie hlášky do diskusie pre neprihlásených uživateľov

- src/components/PageLayout/Banner/Banner.module.scss
- src/components/PageLayout/PageLayout.module.scss
- src/components/PageLayout/PageLayout.tsx
- src/components/PageLayout/TopGrid/TopGrid.module.scss
- src/components/PageLayout/TopGrid/TopGrid.module.scss.d.ts
- src/components/PageLayout/TopGrid/TopGrid.tsx
- src/components/SemesterPicker/Dropdown.module.scss
- src/components/SemesterPicker/Dropdown.tsx
solve https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/205
> Upravit `TopGrid` komponentu podla designu

- src/components/Admin/Admin.tsx
- src/components/Admin/custom/TruncatedTextField.tsx
- src/components/Admin/resources/base/flat-page/FlatpageCreate.tsx
- src/components/Admin/resources/base/flat-page/FlatpageEdit.tsx
- src/components/Admin/resources/base/flat-page/FlatpageList.tsx
- src/components/Admin/resources/base/flat-page/FlatpageShow.tsx
- src/components/Admin/resources/cms/post/PostCreate.tsx
- src/components/Admin/resources/cms/post/PostEdit.tsx
- src/components/Admin/resources/competition/competition/CompetitionShow.tsx
- src/components/Admin/resources/competition/series/SeriesShow.tsx
zakladny management statickoych stranok. funguje, ale pre content bude treba rozumnejsi editor... hlavne s linebreakmi a tak. closes #143 
mam poznacene nedostatky spolu s dalsimi vecami od Peta, issue spravim neskor
> React Admin - Flatpage management

- src/components/SchoolSubForm/SchoolSubForm.tsx
> Fixed registration bug when double clicking school not found

- src/components/Admin/resources/cms/post/PostCreate.tsx
- src/components/Admin/resources/cms/post/PostEdit.tsx
- src/components/Admin/resources/cms/post/PostList.tsx
- src/components/Admin/resources/cms/post/PostShow.tsx
- src/components/Admin/resources/competition/competition/CompetitionEdit.tsx
- src/components/Admin/resources/competition/competition/CompetitionList.tsx
- src/components/Admin/resources/competition/competition/CompetitionShow.tsx
- src/components/Admin/resources/competition/series/SeriesEdit.tsx
- src/components/Admin/resources/competition/series/SeriesList.tsx
- src/components/Admin/resources/competition/series/SeriesShow.tsx
> Deleted ID's from react admin

- src/components/PageLayout/Footer/Footer.tsx
- src/components/PageLayout/MenuMain/MenuMain.tsx
- src/types/api/cms.ts
solve https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/282
> Ask for filtered menu items

- src/components/SemesterPicker/SemesterPicker.tsx
> feat(series): Changed types to match backend responses

- src/components/PageLayout/MenuMain/MenuMain.tsx
> Fix url for semester administration in menu

- src/utils/PageTitleContainer.tsx
close https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/281
> Fix non-changing title for competitions

- src/components/PageLayout/MenuMain/MenuMain.tsx
> Fixes always active menu route

- src/components/Admin/resources/competition/competition/CompetitionList.tsx
- src/components/Admin/resources/competition/competition/CompetitionShow.tsx
> Competition year format without spaces

- src/components/PageLayout/Banner/Banner.module.scss
- src/components/PageLayout/Banner/Banner.tsx
close https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/304
> Fix styles of Banner and make it always visible

- src/components/PageLayout/Authentication/Authentication.module.scss
- src/components/PageLayout/Authentication/Authentication.module.scss.d.ts
- src/components/PageLayout/Authentication/Authentication.tsx
- src/components/PageLayout/LoginForm/LoginForm.tsx
- src/components/PageLayout/LoginFormWrapper/LoginFormWrapper.tsx
- src/components/PageLayout/PasswordResetRequest/PasswordResetRequest.tsx
- src/components/PasswordReset/PasswordReset.tsx
- src/components/Problems/Problems.tsx
- src/components/VerifyEmail/VerifyEmail.tsx
> Login overlay -> dialog

- src/components/PageLayout/Authentication/Authentication.tsx
- src/components/Problems/Problems.tsx
> Added login dialog titles

- src/components/Admin/resources/competition/event/EventCreate.tsx
- src/components/Admin/resources/competition/event/EventEdit.tsx
- src/components/Admin/resources/competition/semester/SemesterCreate.tsx
- src/components/Admin/resources/competition/semester/SemesterEdit.tsx
> Added helper texts in RA

- src/components/Admin/resources/competition/event/EventCreate.tsx
- src/components/Admin/resources/competition/event/EventEdit.tsx
- src/types/api/competition.ts
- src/types/api/generated/competition.ts
> Removed validation from additional_info

- src/components/PublicationUploader/PublicationUploader.tsx
> Remove pdf from publication name in administration

- src/components/Admin/Admin.tsx
- src/components/Admin/custom/MyArrayField.tsx
- src/components/Admin/custom/MyShow.tsx
- src/components/Admin/resources/competition/competition/CompetitionShow.tsx
- src/components/Admin/resources/competition/event/EventShow.tsx
- src/components/Admin/resources/competition/problems/ProblemShow.tsx
- src/components/Admin/resources/competition/semester/SemesterShow.tsx
- src/components/Admin/resources/competition/series/SeriesShow.tsx
- src/components/SemesterPicker/SemesterPicker.tsx
- src/utils/getSemesterName.ts
- src/utils/getSemesterYear.ts
- src/utils/getSeriesName.ts
- src/utils/useDataFromURL.tsx
> admin: record representations based on verbose_name

- src/components/SemesterPicker/Dropdown.module.scss
> Make SemesterPicker scrollable on many options

- src/components/Problems/Problems.tsx
> Add link to rules to problems page

- src/components/PageLayout/MenuMain/MenuMain.tsx
no idea really ci to fixne vysku na mobile, nebol som uplne schopny to dobre otestovat na iphone... ale tak MUI Draweru verim kus viac ako nasej implementacii
> Replace menu solution with MUI Drawer + fullwidth mobile menu

- src/components/Results/ResultsRow.tsx
> Results tooltip

- src/components/Problems/Problems.tsx
> Tips button in Problems page

- src/components/Problems/Problems.tsx
solve https://github.com/ZdruzenieSTROM/webstrom-frontend/issues/250
> Add link to rules to problems page (again)

- src/components/PageLayout/PageLayout.tsx
> Add padding to top of every page

- src/components/Problems/Problem.tsx
> 388 - Mobil - responsive Problem buttons gap and wrapping

- src/components/Admin/resources/competition/event/EventCreate.tsx
- src/components/Admin/resources/competition/event/EventEdit.tsx
- src/components/Admin/resources/competition/event/EventList.tsx
- src/components/Admin/resources/competition/event/EventShow.tsx
> Added location field to event

- src/components/RegisterForm/RegisterForm.tsx
- src/components/SchoolSubForm/SchoolSubForm.tsx
> Registration form texts

- src/components/PageLayout/MenuMain/MenuMain.tsx
- src/components/PageLayout/TopGrid/TopGrid.tsx
- src/components/SemesterPicker/SemesterPicker.tsx
- src/theme.ts
fixes #387 
varianta 1:
varianta 2:
> 387 - Mobil - buttony seminarov

- src/components/Admin/Admin.tsx
- src/components/Admin/dataProvider.ts
- src/components/Admin/resources/competition/event-registration/EventRegistrationCreate.tsx
- src/components/Admin/resources/competition/event-registration/EventRegistrationEdit.tsx
- src/components/Admin/resources/competition/event-registration/EventRegistrationList.tsx
- src/components/Admin/resources/competition/event-registration/EventRegistrationShow.tsx
- src/components/Admin/resources/competition/solution/SolutionCreate.tsx
- src/components/Admin/resources/competition/solution/SolutionEdit.tsx
- src/components/Admin/resources/competition/solution/SolutionList.tsx
- src/components/Admin/resources/competition/solution/SolutionShow.tsx
- src/components/Admin/resources/competition/solution/createSolutionFormData.tsx
- src/components/Results/ResultsRow.tsx
Zacala som sa s tym hrat, zatial to nefunguje, ani neviem ci to bude pouzitelne takto vyberat semester_registration.
closes #245 
closes #348
> RA upload solution

- src/components/SemesterAdministration/SemesterAdministration.tsx
> 450 - matik/malynar - veducovska sekcia - linky na opravovanie uloh

- src/components/SemesterAdministration/SemesterAdministration.tsx
Treba tam pridat handlovanie erroru, teda vypis error hlasky, ktora nam pride z backendu (napr ze seria sa neda uzavriet, lebo nie su opravene vsetky ulohy). A kludne aj nejak inak tam umiestnit tie tlacidla. @rtrembecky nevedel by si sa na to prosim pozriet, neviem ako sa handluju tie errory?
> Buttons for freezing series and semester

- src/components/SemesterPicker/SemesterPicker.tsx
> 437 - swap series and semester pickers

- src/components/SemesterPicker/SemesterPicker.tsx
> Show full title for problems

- src/components/Problems/Problem.tsx
Most notably to be able to read discussion on past problems, but we do not mind also writing e. g. after the author solution has been released.
Resolves #397
> Allow discussion on all problems for everyone.

- src/components/CompetitionPage/UpcomingOrCurrentEventInfo.tsx
- src/components/PublicationUploader/PublicationUploader.tsx
- src/types/api/competition.ts
> 455 using publication types

- src/components/Admin/resources/competition/event-registration/EventRegistrationCreate.tsx
resolves parts of #453 (will edit the issue upon merge)
> RA EventRegistration autofill Grade and School from Profile

- src/components/Admin/Admin.tsx
- src/components/Admin/resources/personal/profiles/ProfileCreate.tsx
- src/components/Admin/resources/personal/profiles/ProfileEdit.tsx
- src/components/Admin/resources/personal/profiles/ProfileList.tsx
- src/components/Admin/resources/personal/profiles/ProfileShow.tsx
> RA Profile

- src/components/SemesterAdministration/SemesterAdministration.tsx
- src/types/api/generated/competition.ts
> Semester administration enhancements

- src/components/CompetitionPage/CompetitionPage.tsx
- src/types/api/competition.ts
fix #504
well bude potreba este prerobit ten archiv aj pre iny typ sutazi ako su jednotnove sutaze
> Improve event publication list

- src/components/Admin/resources/base/flat-page/FlatpageCreate.tsx
- src/components/Admin/resources/base/flat-page/FlatpageEdit.tsx
- src/components/Admin/resources/base/flat-page/FlatpageList.tsx
- src/components/Admin/resources/base/flat-page/FlatpageShow.tsx
> remove sites from flat pages in RA

- package.json
- src/components/Admin/Admin.tsx
- src/components/Admin/AdminLayout.tsx
- src/components/Admin/custom/FilterSidebar.tsx
- src/components/Admin/custom/list-filtering/CompetitionFilterSection.tsx
- src/components/Admin/custom/list-filtering/FilterSidebar.tsx
- src/components/Admin/custom/list-filtering/SemesterFilterSection.tsx
- src/components/Admin/custom/list-filtering/SeriesFilterSection.tsx
- src/components/Admin/dataProvider.ts
- src/components/Admin/resources/cms/post/PostList.tsx
- src/components/Admin/resources/competition/competition/CompetitionList.tsx
- src/components/Admin/resources/competition/event-registration/EventRegistrationList.tsx
- src/components/Admin/resources/competition/event/EventList.tsx
- src/components/Admin/resources/competition/problems/ProblemList.tsx
- src/components/Admin/resources/competition/semester/SemesterList.tsx
- src/components/Admin/resources/competition/series/SeriesList.tsx
- src/components/Admin/resources/competition/solution/SolutionList.tsx
- src/index.scss
- src/utils/useSeminarInfo.ts
- yarn.lock
~potrebuje https://github.com/ZdruzenieSTROM/webstrom-backend/pull/460~
~berme to ako WIP, treba overit este dalsie BE modely a mergnut BE, kym moze toto ist tiez~
resolves #264
> React Admin - Search/Filters/Ordering for Post/Competition/Semester/Series/Problems

- src/components/Posts/Posts.tsx
> Pouzi BE query na filtrovanie postov podla seminaru

- src/components/FormItems/FormAutocomplete/FormAutocomplete.tsx
- src/components/FormItems/FormCheckbox/FormCheckbox.tsx
- src/components/FormItems/FormInput/FormInput.tsx
- src/components/FormItems/FormSelect/FormSelect.tsx
- src/components/FormItems/styles.ts
- src/components/RegisterForm/RegisterForm.tsx
> Redesign Error Inputs

- src/components/Admin/resources/competition/event-registration/EventRegistrationCreate.tsx
> RA: EventRegistration - Create - prefilter Events based on grade and future:true

- src/components/SemesterAdministration/SemesterAdministration.tsx
quick fix after https://github.com/ZdruzenieSTROM/webstrom-frontend/pull/541
> Wrap text to typography

- src/components/PageLayout/MenuMain/MenuMain.tsx
> Let Main Menu be closed by default

- src/colors.ts
- src/components/Admin/custom/PostPreview.tsx
- src/components/Clickable/InlineLink.tsx
- src/components/Clickable/Link.tsx
- src/components/Clickable/buttonStyles.ts
- src/components/Clickable/getDefaultLinkPrefetch.ts
- src/components/Clickable/isExternalLink.ts
- src/components/CloseButton/CloseButton.tsx
- src/components/Crossroad/Crossroad.tsx
- src/components/FormItems/styles.ts
- src/components/Markdown/Texts.tsx
- src/components/PageLayout/Banner/Banner.tsx
- src/components/PageLayout/Footer/Footer.tsx
- src/components/PageLayout/MenuMain/MenuMain.tsx
- src/components/PageLayout/TopGrid/TopGrid.tsx
- src/components/PasswordReset/PasswordReset.tsx
- src/components/ProblemAdministration/ProblemAdministration.tsx
- src/components/RegisterForm/RegisterForm.tsx
- src/components/Results/ResultsRow.tsx
- src/components/SemesterPicker/Dropdown.tsx
- src/components/VerifyEmail/VerifyEmail.tsx
- src/theme.ts
fixes #484
prihodeny daky refactor
> 484 - Inline links design

- src/components/Admin/dataProvider.ts
> RA: pagination

- src/components/Admin/Admin.tsx
- src/components/Admin/AdminLayout.tsx
- src/pages/_app.tsx
> RA: Fix ReactQueryDevtools, introduce 1 min caching

- src/components/ProblemAdministration/ProblemAdministration.tsx
> delete /api from url in uploadLink

- src/theme.ts
> Align post title to left

- src/components/PageLayout/LoginForm/LoginForm.tsx
- src/components/Problems/UploadProblemForm.tsx
> Rework upload solution experience

- src/components/Results/Results.tsx
> Add placeholder text for empty results

- src/components/Problems/Problem.tsx
> Pridané b za počet bodov

- src/components/FormItems/FormInput/FormInput.tsx
- src/components/Profile/ProfileForm.tsx
> Update Edit profile form

- src/components/Problems/Problem.tsx
- src/components/Problems/Problems.tsx
> Tlačidlo na opravovací page konkrétnej úlohy

- src/components/ProblemAdministration/ProblemAdministration.tsx
- src/types/api/competition.ts
> Pridaná informácia o late tagu

- src/components/Admin/resources/competition/solution/SolutionList.tsx
- src/components/Admin/resources/personal/profiles/ProfileList.tsx
- src/components/Admin/resources/personal/schools/SchoolList.tsx
> add search bar to profile, solution and school in RA

- src/components/ProblemAdministration/ProblemAdministration.tsx
- src/theme.ts
> Číslo série na opravovacej stránke

- src/components/Admin/Admin.tsx
- src/components/Admin/resources/personal/profiles/ProfileEdit.tsx
> add Edit of Profile

- src/components/Problems/Discussion.tsx
> Discussion validation

- src/components/Problems/Discussion.tsx
- src/types/api/personal.ts
> Use UserId instead of ProfileId for Discussion

- package.json
- src/components/Markdown/Markdown.tsx
- src/components/Posts/PostMarkdown.tsx
- yarn.lock
> 488 mathjax 2

- src/components/PageLayout/LoginForm/LoginForm.tsx
> Redirect to homepage after login from email verification

- src/components/Problems/Discussion.tsx
> Improve hide reason discussion input

- src/components/Problems/Problem.tsx
- src/types/api/competition.ts
> Pridaný warning po odovzdaní riešenia po termíne v nahlade rieseni

- src/components/Admin/Admin.tsx
- src/components/Admin/custom/MyCreateButton.tsx
- src/components/Admin/resources/competition/event/EventEdit.tsx
- src/components/Admin/resources/competition/event/EventShow.tsx
- src/components/Admin/resources/competition/publication/PublicationCreate.tsx
- src/components/Admin/resources/competition/publication/PublicationEdit.tsx
- src/components/Admin/resources/competition/publication/PublicationList.tsx
- src/components/Admin/resources/competition/publication/PublicationShow.tsx
- src/components/Admin/resources/competition/publication/createPublicationFormData.ts
- src/components/Admin/translations/sk_SK.ts
> 269 ra event publications uplne osobitne nahravanie

- src/components/Crossroad/Crossroad.tsx
- src/theme.ts
> Finalize Root Crossroad

- src/components/NewPasswordSubForm/NewPasswordSubForm.tsx
- src/components/PageLayout/LoginForm/LoginForm.tsx
- src/components/PageLayout/PasswordResetRequest/PasswordResetRequest.tsx
- src/components/PasswordReset/PasswordReset.tsx
- src/components/Profile/PasswordChangeForm.tsx
- src/components/RegisterForm/RegisterForm.tsx
- src/components/SchoolSubForm/SchoolSubForm.tsx
> Refactor password inputs

- src/components/Admin/resources/cms/flat-page/FlatpageCreate.tsx
- src/components/Admin/resources/cms/flat-page/FlatpageEdit.tsx
- src/components/Admin/resources/cms/post/PostCreate.tsx
- src/components/Admin/resources/cms/post/PostEdit.tsx
- src/components/Admin/resources/competition/problems/ProblemCreate.tsx
- src/components/Admin/resources/competition/problems/ProblemEdit.tsx
> Pridaný help text na markdownove fieldy

- src/components/Problems/Problem.tsx
> Zobrazovať pre veduceho iba relevantne tlacidla

- src/components/Markdown/Markdown.tsx
> fix #666 - markdown in flatpage create

- src/components/Profile/ProfileForm.tsx
- src/components/SchoolSubForm/SchoolSubForm.tsx
resolve #639 , partialy also solve #640 - but there is still need to store and loade "other_school_name" from BE
> Profile form changes

- src/components/Archive/Archive.tsx
- src/theme.ts
resolves #485 
novy design archivu - prvy pokus. trochu som sa musel zariadit. revisitneme s Dorot asi
EDIT: Dorot je s tym cajk
> fix #485 - new Archive design

- src/components/Profile/ProfileForm.tsx
- src/components/SchoolSubForm/SchoolSubForm.tsx
- src/types/api/personal.ts
- src/utils/useProfile.ts
> Resolve Profile Form issues

- src/components/Problems/Problems.tsx
> Pridaný prelink na poradie ak je séria po deadline

- src/components/Admin/resources/cms/flat-page/FlatpageCreate.tsx
- src/components/Admin/resources/cms/flat-page/FlatpageEdit.tsx
- src/components/Admin/resources/cms/post/PostCreate.tsx
- src/components/Admin/resources/cms/post/PostEdit.tsx
- src/components/Admin/resources/competition/event-registration/EventRegistrationCreate.tsx
- src/components/Admin/resources/competition/event-registration/EventRegistrationEdit.tsx
- src/components/Admin/resources/competition/event/EventCreate.tsx
- src/components/Admin/resources/competition/event/EventEdit.tsx
- src/components/Admin/resources/competition/problems/ProblemCreate.tsx
- src/components/Admin/resources/competition/problems/ProblemEdit.tsx
- src/components/Admin/resources/competition/semester/SemesterCreate.tsx
- src/components/Admin/resources/competition/semester/SemesterEdit.tsx
- src/components/Admin/resources/competition/series/SeriesCreate.tsx
- src/components/Admin/resources/competition/series/SeriesEdit.tsx
- src/components/Admin/resources/competition/solution/SolutionCreate.tsx
- src/components/Admin/resources/competition/solution/SolutionEdit.tsx
- src/components/Admin/resources/personal/profiles/ProfileCreate.tsx
- src/components/Admin/resources/personal/profiles/ProfileEdit.tsx
- src/components/Admin/resources/personal/schools/SchoolCreate.tsx
- src/components/Admin/resources/personal/schools/SchoolEdit.tsx
> 502 - RA: redundant fullwidths

- docker/Dockerfile
- docker/local-mac/Dockerfile
- src/components/Admin/Admin.tsx
> 681 - turn off telemetry
